version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gracon_frontend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # Necessário para o Next.js observar as mudanças no Docker via WSL/Windows
      # - WATCHPACK_POLLING=true
      # - CHOKIDAR_USEPOLLING=true
    command: npm run dev
